# Generated by Django 5.1.1 on 2024-10-02 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=24, null=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Кличка')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('color', models.CharField(max_length=40, verbose_name='Цвет')),
                ('length_of_coat', models.CharField(max_length=40, verbose_name='Длина шерсти')),
                ('title', models.TextField(max_length=256, verbose_name='Описание')),
                ('gender', models.CharField(max_length=24, verbose_name='Пол')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to='kittensApp.breed', verbose_name='Порода')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='kittensApp.owner', verbose_name='Хозяин')),
            ],
        ),
    ]
