# Generated by Django 5.1.1 on 2024-10-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittensApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitten',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='kitten',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='kitten',
            name='length_of_coat',
        ),
        migrations.RemoveField(
            model_name='kitten',
            name='name',
        ),
        migrations.AddField(
            model_name='kitten',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
        ),
    ]
