# Generated by Django 5.1.1 on 2024-10-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittensApp', '0003_remove_kitten_owner_kitten_user_delete_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kittens', to='kittensApp.breed', verbose_name='Порода'),
        ),
    ]
