# Generated by Django 5.1.1 on 2024-10-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittensApp', '0004_alter_kitten_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitten',
            options={'verbose_name': 'Котята', 'verbose_name_plural': 'Котят'},
        ),
    ]
